-- MySQL Script generated by MySQL Workbench
-- Sat Nov 25 15:47:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pokemon_captured`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pokemon_captured` (
  `id_pokemon` INT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `abilities` VARCHAR(255) NOT NULL,
  `power` VARCHAR(255) NULL,
  `base_experience` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_pokemon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pokemon_battle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pokemon_battle` (
  `id_batalha` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `enemy_name` VARCHAR(255) NOT NULL,
  `enemy_power` VARCHAR(255) NOT NULL,
  `user_pokemon_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_batalha`),
  INDEX `fk_user_pokemon_id_idx` (`user_pokemon_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_pokemon_id`
    FOREIGN KEY (`user_pokemon_id`)
    REFERENCES `mydb`.`pokemon_captured` (`id_pokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
